# Generated by Django 4.0.4 on 2022-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='N/A', max_length=255)),
                ('flight', models.CharField(default='N/A', max_length=255)),
                ('_from', models.CharField(default='N/A', max_length=255)),
                ('airline', models.CharField(default='N/A', max_length=255)),
                ('aircraft', models.CharField(default='N/A', max_length=255)),
                ('status', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='N/A', max_length=255)),
                ('flight', models.CharField(default='N/A', max_length=255)),
                ('destination', models.CharField(default='N/A', max_length=255)),
                ('airline', models.CharField(default='N/A', max_length=255)),
                ('aircraft', models.CharField(default='N/A', max_length=255)),
                ('status', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
    ]
