# Generated by Django 4.0.4 on 2022-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasablancaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivals',
            name='date',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='arrivals',
            name='day',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='depatures',
            name='date',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='depatures',
            name='day',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
