# Generated by Django 4.0.4 on 2022-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasablancaAPI', '0002_arrivals_date_arrivals_day_depatures_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivals',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='depatures',
            name='date',
            field=models.DateField(),
        ),
    ]
